# Generated by Django 4.2.1 on 2023-10-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='created_2ru_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
